### ISSUE TITLE
Will it support Java 17 in the future?

### ISSUE THREAD

**Issue by DarkTinia** [nntzuekai/Respector#1]
Wonderful project! Will it support Java 17 in the future? I've noticed many projects are adopting Java 17 for compilation. Thank you for your response.

**Comment by nntzuekai** [comment]
Thank you! 

Unfortunately it does not seem very viable at this point. The underlying program analysis framework, Soot, supports up to Java 9 [https://github.com/soot-oss/soot?tab=readme-ov-file#soot-supports-java-9-modules-now](https://github.com/soot-oss/soot?tab=readme-ov-file#soot-supports-java-9-modules-now). Although Soot has been overhauled, the new SootUp framework also seems to have limited supports for Java>10 [https://github.com/soot-oss/SootUp/wiki/Supported-constructs-of-the-Java-language](https://github.com/soot-oss/SootUp/wiki/Supported-constructs-of-the-Java-language). As an alternative to Soot, WALA has a better support for newer Java versions, but it would be quite an effort to rewrite our tool using WALA, and we don't plan to switch to WALA. Instead, I do plan to adopt Java PathFinder to improve the symbolic analysis in the future, but it so far doesn't fully support Java 11+, either [https://github.com/javapathfinder/jpf-core/wiki/GSoC-2024-Project-Ideas#support-java-11-for-spf](https://github.com/javapathfinder/jpf-core/wiki/GSoC-2024-Project-Ideas#support-java-11-for-spf) .
